version: '1'

services:
  mysql:
    image: mysql
    ports:
      - "3307:3306"
    env_file:
      - project-school-config-mysql.envfile
  projectschool:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    image: projectschool
    ports:
      - "8081:8080"
    env_file:
      - project-school-config-docker.envfile
    restart: always
