apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: project-school
  name: project-school-deployment
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 8080
  selector:
    app: project-school
  type: LoadBalancer
status:
  loadBalancer: {}
